title: Four Corners Science and Computing Club
email: 4cscc@nau.edu
description: >-
  Four Corners Science and Computing Club (4CSCC)
domain: four-corners-scientific-computing.org
baseurl: "/"
url: https://four-corners-scientific-computing.org
github_username:  4cscc

# Build settings
theme: minima
plugins:
  - jekyll-feed

minima:
  skin: dark

header_pages:
  - about.md
  - student_projects.html
  - friends-of-4CSCC.md
  - team.html
  - lab-manual.md